[package]
name = "gtk-pwsafe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { package="gtk4", version="0.4.8", features = ["v4_2", "v4_4", "v4_6"]}
